/**
 * Creates a memoized version of a function.
 * The memoized function caches the results of function calls and returns the cached result
 * when the same inputs occur again.
 *
 * @template A The type of the arguments array for the function `fn`.
 * @template R The return type of the function `fn`.
 * @template K The type of the cache key generated by `argsToCacheKey`.
 * @param fn The function to memoize.
 * @param argsToCacheKey A function that converts the arguments of `fn` into a cache key.
 *                       The cache key should uniquely identify the set of arguments.
 * @returns A new function that is a memoized version of `fn`.
 */
export const memoizeFunction = <const A extends readonly unknown[], R, K>(
  fn: (...args: A) => R,
  argsToCacheKey: (...args: A) => K,
): ((...args: A) => R) => {
  const mut_cache = new Map<K, R>();

  return (...args: A): R => {
    const key = argsToCacheKey(...args);
    const cachedValue = mut_cache.get(key);

    if (cachedValue !== undefined) {
      return cachedValue;
    } else {
      const result = fn(...args);

      mut_cache.set(key, result);

      return result;
    }
  };
};
